### ISSUE TITLE
gh-actionlint has not been updated lately, missing lots of updates to rhysd/actionlint

### ISSUE THREAD

**Issue by halostatue** [cschleiden/gh-actionlint#2]
On the same actions, `gh actionlint` reports:

```
.github/workflows/deploy-dev.yml:32:26: property "ref" is not defined in object type {} [expression]
   |
32 |           INPUT_REF: ${{ inputs.ref }}
   |                          ^~~~~~~~~~
```

`actionlint` by itself reports nothing.

**Comment by ChrisCarini** [comment]
It looks like https://github.com/cschleiden/gh-actionlint/pull/10 has this `gh` extension pulling in the latest version of `actionlint`, but it does not seem that a new release of `gh-actionlint` has been published yet.

@cschleiden - when you have a moment, do you mind publishing a version? Based on https://github.com/cschleiden/gh-actionlint/blob/main/.github/workflows/release.yml & https://github.com/cli/gh-extension-precompile , it sounds like you need to..

> either push a new git tag like v1.0.0 to your repository, or create a new Release and have it initialize the associated git tag.

**Comment by cschleiden** [comment]
Thanks! Should be done now 🤞

**Comment by ChrisCarini** [comment]
Perfect, thank you @cschleiden !
